/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    int choose=MainMenu.chC;
    Connection conn =null;
    PreparedStatement ps =null;
    ResultSet rst=null;
    public Course() {
        initComponents();
        rightToLeft();
        insertNameDoctor();
        if(choose==2)
        {
            this.setTitle("تعديل الكورس");
            jButton1.setIcon(new ImageIcon("E:\\University\\src\\images\\editS.jpg"));
            name.setEnabled(false);
            hours.setEnabled(false);
            salary.setEnabled(false);
            second.setEnabled(false);
            first.setEnabled(false);
            doctor.setEnabled(false);
        }
        else if(choose ==3)
        {
            this.setTitle("حذف الكورس");
            jButton1.setIcon(new ImageIcon("E:\\University\\src\\images\\deleteStudent.jpg"));
            name.setEnabled(false);
            hours.setEnabled(false);
            salary.setEnabled(false);
            second.setEnabled(false);
            first.setEnabled(false);
            doctor.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        hours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctor = new javax.swing.JComboBox<>();
        first = new javax.swing.JRadioButton();
        second = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("رقم المادة ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 33, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("إسم المادة ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("عدد الساعات");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 109, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 209, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        hours.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("سعر الساعات");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 147, -1, -1));

        salary.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("دكتور المادة");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 185, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("الفصل  الدراسى");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 225, -1, -1));

        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, -1));

        buttonGroup1.add(first);
        first.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        first.setText("الاول");
        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        buttonGroup1.add(second);
        second.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        second.setText("الثانى");
        getContentPane().add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-Male-User.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 400, 360));

        setSize(new java.awt.Dimension(395, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(choose==1)
           insert();
       else if(choose==2)
       {
         if(id.getText().equals(""))
           JOptionPane.showMessageDialog(null, "يرجى إدخال رقم المادة ","ادخل رقم المادة",JOptionPane.INFORMATION_MESSAGE);
         update();
       }
       else
           delete();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
      
        if(evt.getKeyCode()== evt.VK_ENTER && choose==2)
        {
            try{
            conn=ConnectionDataBase.connect();
            ps=conn.prepareStatement("select * from course where idCourse='"+Integer.parseInt(id.getText())+"'");
            rst=ps.executeQuery();
            if(rst.next())
            {
                id.setEnabled(false);
                name.setEnabled(true);
                name.setText(rst.getString(2));
                
                hours.setEnabled(true);
                hours.setText(rst.getString(3));
                
                salary.setEnabled(true);
                salary.setText(rst.getString(4));
                
                doctor.setEnabled(true);
                String nameDoc=rst.getString(5);
                doctor.setSelectedItem(nameDoc);
                
                first.setEnabled(true);
                second.setEnabled(true);
                
                int sem=Integer.parseInt(rst.getString(6));
                if(sem==2)
                    second.setSelected(true);
                else
                    first.setSelected(true);
            }else{
                    JOptionPane.showMessageDialog(null, "رقم المادة غير موجود","غير موجود",JOptionPane.INFORMATION_MESSAGE);
            }
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_idKeyPressed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> doctor;
    private javax.swing.JRadioButton first;
    private javax.swing.JTextField hours;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    private javax.swing.JRadioButton second;
    // End of variables declaration//GEN-END:variables

    private void rightToLeft() {
        id.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        hours.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        salary.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        first.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        second.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
}

    private void insert() {
        String term=first.getText();
        String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
        int sem=1;
        if(second.isSelected())
            sem=2;
        if(id.getText().equals(""))
            miss+="رقم المادة"+"\n";
        if(name.getText().equals(""))
            miss+="إسم المادة"+"\n";
        if(hours.getText().equals(""))
            miss+="عدد الساعات"+"\n";
        if(salary.getText().equals(""))
            miss+="سعر الساعات"+"\n";
        if(doctor.getSelectedIndex()==-1)
            miss+="دكتور المادة"+"\n";
        if(second.isSelected())
            term=second.getText();
        if(!first.isSelected() && !second.isSelected())
             miss+="الفصل الدراسى"+"\n";
        if(!(id.getText().equals("") && name.getText().equals("") && hours.getText().equals("") && salary.getText().equals("") && doctor.getSelectedIndex()==-1 )&&(first.isSelected() || second.isSelected()))
        {
            conn=ConnectionDataBase.connect();
            try {
                
                ps=conn.prepareStatement("select * from course where idCourse='"+Integer.parseInt(id.getText())+"'");
                rst=ps.executeQuery();
                if(!rst.next())
                {
                    ps=conn.prepareStatement("insert into course values('"+Integer.parseInt(id.getText())+"','"+name.getText()+"' ,'"+Integer.parseInt(hours.getText())+"','"+Integer.parseInt(salary.getText())+"','"+doctor.getSelectedItem()+"','"+sem+"')");
               //   ps=conn.prepareStatement("insert into course values('"+Integer.parseInt(id.getText())+"','"+name.getText()+
                       //     "',,'"+Integer.parseInt(hours.getText())+"','"+Integer.parseInt(salary.getText())+"')");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "تمت إضافة المادة بنجاح","تمت الاضافة",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }else
                    JOptionPane.showMessageDialog(null, "رقم المادة موجود مسبقا ","موجود",2);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }finally{
                try {
                    conn.close();
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
            
        } else
            JOptionPane.showMessageDialog(null, miss, "فقد بيانات الدخول",2);
        
    }

    private void update() {
        
        String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
     
        if(name.getText().equals(""))
            miss+="إسم المادة"+"\n";
        if(hours.getText().equals(""))
            miss+="عدد الساعات"+"\n";
        if(salary.getText().equals(""))
            miss+="سعر الساعات"+"\n";
        if(doctor.getSelectedIndex()==-1)
            miss+="دكتور المادة"+"\n";
          
        if(!first.isSelected() && !second.isSelected())
             miss+="الفصل الدراسى"+"\n";
        int sem=1;
          if(second.isSelected())
              sem=2;
        if(!( name.getText().equals("") && hours.getText().equals("") && salary.getText().equals("") && doctor.getSelectedIndex()==-1 )&&(first.isSelected() || second.isSelected()))
        {
            try {
                 
                conn=ConnectionDataBase.connect();
                ps=conn.prepareStatement("update course set nameC='"+name.getText()+"', hoursC='"+Integer.parseInt(hours.getText())+"',salaryOneHour='"+Integer.parseInt(salary.getText())+"',nameDoctor='"+doctor.getSelectedItem()+"',semester='"+sem+"' where idCourse='"+Integer.parseInt(id.getText())+"'");
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "تم تعديل المادة بنجاح","تم التعديل",JOptionPane.INFORMATION_MESSAGE);
                clear();
                name.setEnabled(false);
                hours.setEnabled(false);
                salary.setEnabled(false);
                second.setEnabled(false);
                first.setEnabled(false);
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
         }
    
        }else{
                JOptionPane.showMessageDialog(null,miss,"فقدت بيانات الدخول ",2);
        }
    }

    private void delete() {
     String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
        if(id.getText().equals(""))
            miss+="رقم المادة"+"\n";
      if(!id.getText().equals(""))
        {
         try {
             conn=ConnectionDataBase.connect();
             ps=conn.prepareStatement("select * from course where idCourse='"+Integer.parseInt(id.getText())+"'");
             rst=ps.executeQuery();
            
             if(rst.next())
             {
                     ps=conn.prepareStatement("delete from course where idCourse='"+Integer.parseInt(id.getText())+"'");
                      ps.execute();
                JOptionPane.showMessageDialog(null, "تم حذف الكورس بنجاح","تم حذف الكورس",JOptionPane.INFORMATION_MESSAGE);
                id.setText("");
             }else{
                 JOptionPane.showMessageDialog(null,"رقم الطالب غير موجود","غير موجود",2);
             }
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage());
         }finally{
             try {
                 conn.close();
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
             }
         }
            
        }else{
                JOptionPane.showMessageDialog(null,miss,"فقدت بيانات الدخول ",2);
        }
    }

    private void insertNameDoctor() {
        conn=ConnectionDataBase.connect();
        try {
            ps=conn.prepareStatement("select nameD from doctor");
            rst=ps.executeQuery();
            while(rst.next())
                doctor.addItem(rst.getString("nameD"));
            doctor.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void clear() {
        id.setText("");
        name.setText("");
        hours.setText("");
        salary.setText("");
        doctor.setSelectedItem(-1);
       first.setSelected(false);
       second.setSelected(false);
    }
}