
package university;

import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Student extends javax.swing.JFrame {
   int choose;
   Connection conn=null;
   PreparedStatement ps=null;
    ResultSet rst=null;
    public Student() {
        initComponents();
        id.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        mobile.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        choose =MainMenu.ch;
        if(choose==2)
        {
            this.setTitle("تعديل طالب ");
            name.setEnabled(false);
            mobile.setEnabled(false);
            male.setEnabled(false);
            female.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jButton1.setIcon(new ImageIcon("E:\\University\\src\\images\\editS.jpg"));
        }
           if(choose==3)
           {
                this.setTitle("حذف طالب ");
                name.setEnabled(false);
                mobile.setEnabled(false);
                male.setEnabled(false);
                female.setEnabled(false);
                jLabel2.setEnabled(false);
                jLabel3.setEnabled(false);
                jLabel4.setEnabled(false);
                jButton1.setIcon(new ImageIcon("E:\\University\\src\\images\\deleteStudent.jpg"));
             
           }    
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("إضافة طالب");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("رقم الطالب ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 40, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("إسم الطالب");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("رقم الجوال");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 80, 220, -1));
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 120, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("الجنس");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 40, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        male.setText("ذكر");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        female.setText("انثى");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-Male-User.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 310));

        setSize(new java.awt.Dimension(397, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        MainMenu m =new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(choose==1)
           try {
               insert();
       } catch (SQLException ex) {
           Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
       }
       else if(choose==2)
           update();
       else
           delete();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            if(id.getText().equals(""))
                JOptionPane.showMessageDialog(null, "رقم التعريف فارغ");
            else
            {
              conn =ConnectionDataBase.connect();
                try {
                    ps=conn.prepareStatement("select * from student where id = '"+Integer.parseInt(id.getText())+"'");
                    rst=ps.executeQuery();
                    if(rst.next())
                    {
                        id.setEnabled(false);
                        
                        name.setText(rst.getString(2));
                        name.setEnabled(true);
                        
                        mobile.setText(rst.getString(4));
                        mobile.setEnabled(true);
                        
                        String gender =rst.getString(5);
                        if(gender.equals(male.getText()))
                            male.setSelected(true);
                        else 
                            female.setSelected(true);
                        male.setEnabled(true);
                        female.setEnabled(true);
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                  try {
                      conn.close();
                  } catch (SQLException ex) {
                      
                  }
                }
            }
        }
    }//GEN-LAST:event_idKeyPressed

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

    private void insert() throws SQLException {
        String gender=male.getText();
        if(female.isSelected())
            gender=female.getText();
        String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
        if(id.getText().equals(""))
            miss+="رقم الطالب"+"\n";
        if(name.getText().equals(""))
            miss+="إسم الطالب"+"\n";
        if(mobile.getText().equals(""))
            miss+="رقم الموبايل"+"\n";
        if(!male.isSelected() && !female.isSelected())
             miss+="الجنس"+"\n";
        if(!id.getText().equals("") && !name.getText().equals("") && !mobile.getText().equals("") && (male.isSelected() || female.isSelected()))
        {
            conn=ConnectionDataBase.connect();
            try {
                ps=conn.prepareStatement("select * from student where id ='"+Integer.parseInt(id.getText())+"'");
                rst=ps.executeQuery();
                if(rst.next())
                    JOptionPane.showMessageDialog(null, "رقم الطالب موجود مسبقا ","موجود",2);
                else
                {
                    ps=conn.prepareStatement("insert into student values('"+Integer.parseInt(id.getText())+"','"+name.getText()+
                            "','123','"+mobile.getText()+"','"+gender+"','0','0','0','0')");
                     ps.execute();
                    JOptionPane.showMessageDialog(null, "تمت اضافة الطالب بنجاح");
                    clear();
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                conn.close();
            }
        }
        else
            JOptionPane.showMessageDialog(null, miss, "فقد بيانات الدخول",2);
            
    }

    private void update() {
        String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
        String gender=male.getText();
        if(female.isSelected())
            gender=female.getText();
        if(id.getText().equals(""))
            miss+="رقم الطالب"+"\n";
         if(!id.getText().equals("") )
         {
             try {
                    conn=ConnectionDataBase.connect();
                    ps=conn.prepareStatement("update student set name= '"+name.getText()+"',mobile='"+mobile.getText()+"', gender='"+gender+"'where id = '"+Integer.parseInt(id.getText())+"'");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "تم تعديل الطالب بنجاح","تعديل الطالب",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                    id.setEnabled(true);
                    name.setEditable(false);
                    mobile.setEnabled(false);
                    male.setEnabled(false);
                    female.setEnabled(false);
                 } catch (SQLException ex) {
                        Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                 }finally{
                            try {
                                conn.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                            }
                 }
         }
        else
            JOptionPane.showMessageDialog(null, miss, "فقد بيانات الدخول",2);
       
       
    }

    private void delete() {
       String miss ="لقد نسيت ادخال البيانات التالية"+"\n";
        if(id.getText().equals(""))
            miss+="رقم الطالب"+"\n";
         if(!id.getText().equals("") )
         {  
           try {
                    conn=ConnectionDataBase.connect();
                    ps=conn.prepareStatement("delete from student where id ='"+Integer.parseInt(id.getText())+"'");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "تم حذف الطالب بنجاح","حذف الطالب",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                    id.setText("");
              } catch (SQLException ex) {
                      Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
           }finally{
               try {
                   conn.close();
               } catch (SQLException ex) {
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
         }
         
        else
            JOptionPane.showMessageDialog(null, miss, "فقد بيانات الدخول",2);
    }

    private void clear() {
       id.setText("");
       name.setText("");
       mobile.setText("");
       
       male.setSelected(false);
       female.setSelected(false);
    }
}
